### PR TITLE
Fix sdk data

### PR DESCRIPTION
**Pull request by joeandrews**
## Summary

Additional fixes for the SDK

### CODE REVIEW

**Review by LeilaWang — APPROVED** [review]

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.8.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 0.17.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.18.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.20.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 2.4.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.6.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.3.2 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.1.4 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
