### PR TITLE
Add mainnet contract addresses

### PR DESCRIPTION
**Pull request by thomas-waite**
## Summary
Add `mainnet` contract addresses

### CODE REVIEW

**Comment by ArnSch** [comment]
:tada: This PR is included in version 1.15.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by ArnSch** [comment]
:tada: This PR is included in version 1.4.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.19.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.5.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 0.17.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 2.4.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.3.2 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.1.4 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
