### PR TITLE
feat(protocol): update zkAssetBase confidentialApprove to allow self-approval

### PR DESCRIPTION
**Pull request by ArnSch**
## Summary

This PR allows a note owner to call `confidentialApprove` without a signature, enabling smart contracts to own and spend notes.

## Description

To allow for smart contract wallets and some more complex flows on-chain, it is desirable for smart contracts to be able to own, and spend zkNotes. Given smart contracts do not have associated private keys, standard permissioning flows making use of ECDSA signatures will not work.

This PR adapts the `confidentialApprove` function on `zkAssetBase` to allow a note to be approved without a signature if the `msg.sender` is the note owner. To achieve this, it was necessary to modify our replay protection check, to only assert that non-zero-length signatures haven't been previously used.

```
        require(signatureLog[signatureHash] != true, "signature has already been used");
        if (_signature.length != 0) {
            signatureLog[signatureHash] = true;
        }
```

As mentioned above, permissioning on who can make such a zero-length-signature call is strictly defined in `validateSignature`, which asserts that a signature approving a particular note can only be empty if the `msg.sender` is the current owner of the note in question.

## Types of changes

 * New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by thomas-waite — APPROVED** [review]
Looks good!

**Comment by joeandrews** [comment]
:tada: This PR is included in version 0.17.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.18.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.20.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 2.4.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.6.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.3.2 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.1.4 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.9.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
