### PR TITLE
Fix issues in sdk

### LINKED ISSUE #468: `balanceOfLinkedToken` returns an overflown number
## Expected Behaviour

`balanceOfLinkedToken` should return a BigNumber or string

## Current Behaviour

`balanceOfLinkedToken` returns a javascript number, which may overflow

## Possible Solution

I think the customary thing to do here is to return some instance of some big number library, but returning a string should work too.

## Steps to Reproduce (for bugs)

1. Create a zkAsset in Rinkeby with the address from the docs: `const asset = await window.aztec.zkAsset('0x70c23EEC80A6387464Af55bD7Ee6C8dA273C4fb4');`
2. Mint a huge amount of the linked token (`0x5B7825EA998Db74E7e43736D91459C1B0f0AdcA9`). I did `10000000000000000000` (1E19)
3. Call `asset.balanceOfLinkedToken()`

## Your Environment

I used the aztec library from `https://sdk.aztecprotocol.com/aztec.js`

### PR DESCRIPTION
**Pull request by LeilaWang**
## Summary

This PR fixes multiple minor issues in the sdk

- show aztec address instead of real address in register view
- return big numbers from all linked token related apis (Closes #468 )
- correctly format large values in the ui
- make subscriptions and callbacks more reliable while switching accounts
- remove dynamic data like apiKey or network id from local storage to avoid conflicts between different dapps

This PR also introduces a mechanism to modify indexedDB and local storage if necessary in the future versions of the sdk.

## Testing instructions

Tests for indexedDB migrations are in `packages/extension/src/background/tasks/__tests__/migrateIndexedDB.spec.js`

Tests for upgradable local storage data are integrated into existing tests in `packages/extension/src/background/services/NoteService/__tests__/`

## Types of changes

Bug fix (non-breaking change which fixes an issue)

New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by joeandrews — APPROVED** [review]

**Comment by ArnSch** [comment]
@LeilaWang just pinging about lint issue when you have a second.

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.19.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.5.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.7.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 0.17.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.18.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 2.4.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.3.2 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This PR is included in version 1.1.4 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Pull request merged**
